kernel.mk: fix gator_driver dependency
Make gator_driver dependent on the kernel build step to fix:

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

Change-Id: I6eb1323c01a2dc75a861f7213ce7d53fffa831fd
Signed-off-by: Zach Pfeffer <zach.pfeffer@linaro.org>